### PR TITLE
Update decimal-data-type.md

### PR DESCRIPTION
**Pull request by kfir-firebolt**

### CODE REVIEW

**Review by TimoDoering-firebolt — APPROVED** [review]

**Comment by molly-firebolt** [comment]
@kfir-firebolt is there a ticket for this new function support? What version does that apply to? I think this should also be added to release notes for that version.

**Comment by kfir-firebolt** [comment]
> @kfir-firebolt is there a ticket for this new function support? What version does that apply to? I think this should also be added to release notes for that version.

@molly-firebolt there is no new function this was just for changing the beta to not beta

**Comment by molly-firebolt** [comment]
@kfir-firebolt this commit also added the ZEROIFNULL function to the list of supported functions - in which version can customers use that function with DECIMAL, is that new or was it just missed before ?

**Comment by kfir-firebolt** [comment]
> @kfir-firebolt this commit also added the ZEROIFNULL function to the list of supported functions - in which version can customers use that function with DECIMAL, is that new or was it just missed before ?

@molly-firebolt its not, I dont know why github shows this wierd diff, look it uses minus plus the same line

**Pull request closed without merging**
